version: 0.0
os: linux
files:
  # unzip the build artifact in ~/app/release
  - source: /
    destination: /home/ec2-user/app/release
permissions:
  # change permissions from root to ec2-user
  - object: /home/ec2-user/app/release
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    # stops the currently running instance of the application, if one exists
    - location: deploy/stop-old-service.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    # after copying the release files to their final dest, build node dependencies on ec2
    - location: deploy/install-npm-deps.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    # start the new build of the application on the ec2 instance
    - location: deploy/start-new-service.sh
      timeout: 20
      runas: ec2-user

