version: 0.2

phases:
  pre_build:
    commands:
      # run 'npm install' using versions in package-lock.json
      - rm -rf ./node_modules/
      - npm ci
  build:
    commands:
      - npm rebuild
  post_build:
    commands:
      - ln -s ./node_modules/pm2/bin/pm2 /usr/bin
      - ln -s ./node_modules/pm2/bin/pm2 /usr/local/bin
      - npm start
artifacts:
  files:
    - buildspec.yml
    - appspec.yml
    - server.js
    - package.json
    - 'deploy/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
