version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      # run 'npm install' using versions in package-lock.json
      - npm rebuild
      - npm install
      - ln -s ./node_modules/pm2/bin/pm2 /usr/bin
  build:
    commands:
      - npm run build
  post_build:
    run-as: ec2-user
    commands:
      - npm start
artifacts:
  files:
    - buildspec.yml
    - appspec.yml
    - server.js
    - package.json
    - 'deploy/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
