version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo "CODEBUILD_SRC_DIR -> $CODEBUILD_SRC_DIR"
      # run 'npm install' using versions in package-lock.json
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    run_as: ec2-user
    commands:
      - npm start
artifacts:
  files:
    - start-service.sh
    - stop-service.sh
    - server.js
    - package.json
    - appspec.yml
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'deploy/config/*'
